language: haskell
branches:
  only:
  - hakyll
install:
- cabal install hakyll
- ghc --make site.hs
before_script:
- cd _site
- git checkout master
- git pull origin master
- cd ..
script: "./site build"
after_script:
- cd _site
- git status
- git add --all
- git config --global user.email "$GH_EMAIL"
- git config --global user.name "Travis"
- git commit -m "publish $(date '+%m/%d/%y %H:%M')"
- git push "$REPO_URL" master | grep -v http
- cd ..
before_install:
- openssl aes-256-cbc -K $encrypted_dcab2b6bd260_key -iv $encrypted_dcab2b6bd260_iv
  -in circle.enc -out ~\/.ssh/circle -d
- ssh-add ~\/.ssh/circle -d
