language: haskell
branches:
  only:
  - hakyll
install:
- cabal install hakyll
- ghc --make site.hs
before_script:
- cd _site
- git checkout master
- git pull origin master
- cd ..
script: "./site build"
after_script:
- cd _site
- git status
- git add --all
- git config --global user.email "$GH_EMAIL"
- git config --global user.name "Travis"
- git commit -m "publish $(date '+%m/%d/%y %H:%M')"
- git push "$REPO_URL" master | grep -v http
- cd ..
GH_NAME=Jader Martins:
  secure: eISrjWPjYCMDbYtyFtZV/KOUdAyLhz3yIoOW51/qTS6gRZHZw0xGyXX9HCl7pMemwl6QvnXIaocjbkHVTGllQdjG0NChKWEtInH4l4S5jpzIl0Pa/o3/OzVkI2ugvB+cqZb0BIqXypwDJ3aKxDSmWmfJnTh+0Syjx2KaDxHZtB3bcg+EyevbKqFbHF+6VAduxMIudOlX9dNgxElCdXGJdOnVR3+MyEEoGsvmRmUiOzWmje/FQ6qDYOY5oTQZ9fLdMeRaQsBEwWLYFGi02aH0FM+U1QzVRm5w6g9Z7zDejgqorOV/az5QnfNYT588jlaeDn77l0AP7YsmK1ujtgVF7Bw5Q0nWp4j7CldaQuNDKxuBYiicSC7b2cKdaet200eqSHdoMKZdsHIrUqRUxNBcvrpboOQaYiZIqSdADzzV2WWS1G5ob7xtEIrPrwVGxQvGmbWrtsme90lFRKRNDSlb4ZcOIaQyhWBuGqdtQGUV47HXTrmnlIzGQG99lUG2M+4bIYHrBhsc4zm2WPLiO+omMrlI/QYW0PU7UGgawX8ynIc3dpiSXv7SNMCNK1A00TsLNPrHZSOpBsPMIv2HoQ7g9vmXckkGNCOFuqqD/bxodn9Z+jwwKW9BlQDi95l133UAWkyPv2GESPY3RUE/jTMBFV5b/tPFjCs+h6xo/7UV00s=
