language: haskell
branches:
  only:
  - hakyll
install:
- cabal update
- cabal install hakyll
- ghc --make site.hs
before_script:
- cd _site
- git checkout master
- git pull origin master
- cd ..
script: "./site build"
after_script:
- cd _site
- git status
- git add --all
- git config --global user.email "$GH_EMAIL"
- git config --global user.name "Travis"
- git commit -m "publish $(date '+%m/%d/%y %H:%M')"
- git push "$REPO_URL" master | grep -v http
- cd ..
# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
